[package]
name = "smmstore"
version = "0.1.0"
authors = ["Jeremy Soller <jeremy@system76.com>"]
edition = "2018"

[dependencies]
redox_uefi = { git = "https://gitlab.redox-os.org/tcrawford/uefi.git", branch = "fvb" }
plain = "0.2"
